services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./backend:/var/www/html:z
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
